const links = [
  {
    id: 1,
    name: "Messenger",
    url: "https://m.me/",
    description: "Facebook Messenger - connect with people instantly.",
    tags: ["social", "messaging"],
    categories: "Communication",
  },
  {
    id: 2,
    name: "YouTube",
    url: "https://www.youtube.com/",
    description: "Video platform for watching and sharing content.",
    tags: ["video", "entertainment"],
    categories: "Entertainment",
  },
  {
    id: 3,
    name: "Google Calendar",
    url: "https://calendar.google.com/calendar/u/0/r?tab=wc&pli=1",
    description: "Google Calendar for managing events and reminders.",
    tags: ["productivity", "calendar"],
    categories: "Productivity",
  },
  {
    id: 4,
    name: "GitHub",
    url: "https://github.com/",
    description: "Platform for version control and collaboration.",
    tags: ["code", "collaboration"],
    categories: "Development",
  },
  {
    id: 5,
    name: "ChatGPT",
    url: "https://chat.openai.com/",
    description: "AI-powered chat platform by OpenAI.",
    tags: ["AI", "assistant"],
    categories: "AI",
  },
  {
    id: 6,
    name: "Gmail",
    url: "https://mail.google.com/mail/u/0/",
    description: "Google's email service for communication.",
    tags: ["email", "communication"],
    categories: "Communication",
  },
  {
    id: 7,
    name: "Google Meet",
    url: "https://meet.google.com/taw-vfxv-rbu",
    description: "Video conferencing service by Google.",
    tags: ["video call", "communication"],
    categories: "Communication",
  },
  {
    id: 8,
    name: "My Courses - ELF",
    url: "https://elf.ku.edu.np/my/courses.php",
    description: "Online learning platform for course management.",
    tags: ["education", "learning"],
    categories: "Education",
  },
  {
    id: 9,
    name: "Google Classroom",
    url: "https://classroom.google.com/u/0/h",
    description: "Google Classroom for managing assignments and classes.",
    tags: ["education", "management"],
    categories: "Education",
  },
  {
    id: 10,
    name: "9anime",
    url: "https://9animetv.to/home",
    description: "Watch anime shows online.",
    tags: ["anime", "streaming"],
    categories: "Entertainment",
  },
  {
    id: 11,
    name: "Canvas",
    url: "https://canvas.instructure.com/courses/10215650",
    description: "Learning management system for courses.",
    tags: ["education", "courses"],
    categories: "Education",
  },
  {
    id: 12,
    name: "Is it down? Check at Down for Everyone or Just Me",
    url: "https://downforeveryoneorjustme.com/",
    description: "Check if a website is down for everyone or just you.",
    tags: ["website status", "tools"],
    categories: "Utilities",
  },
  {
    id: 13,
    name: "Free Courses | Real Discount",
    url: "https://www.real.discount/filter/?category=3&subcategory=it-certification&store=All&duration=All&price=All&rating=All&language=All&search=&submit=Filter",
    description: "Platform for finding discounted and free courses.",
    tags: ["education", "courses"],
    categories: "Education",
  },
  {
    id: 14,
    name: "Flutter Layout Cheat Sheet",
    url: "https://medium.com/flutter-community/flutter-layout-cheat-sheet-5363348d037e",
    description: "Cheat sheet for Flutter layouts.",
    tags: ["Flutter", "UI"],
    categories: "Development",
  },
  {
    id: 15,
    name: "Material Palette",
    url: "https://www.materialpalette.com/",
    description: "Material design color palette generator.",
    tags: ["design", "colors"],
    categories: "Design",
  },
  {
    id: 16,
    name: "Multidex Issue in Flutter",
    url: "https://flutteragency.com/how-to-deal-with-multidex-issue-in-flutter/",
    description: "Guide on handling multidex issues in Flutter.",
    tags: ["Flutter", "debugging"],
    categories: "Development",
  },
  {
    id: 17,
    name: "just_audio Flutter Package",
    url: "https://pub.dev/packages/just_audio",
    description: "Flutter package for handling audio.",
    tags: ["Flutter", "audio"],
    categories: "Development",
  },
  {
    id: 18,
    name: "Playing short audio clips in Flutter",
    url: "https://suragch.medium.com/playing-short-audio-clips-in-flutter-with-just-audio-3c80eb7eb6ea",
    description: "Guide on playing audio in Flutter using just_audio.",
    tags: ["Flutter", "audio"],
    categories: "Development",
  },
  {
    id: 19,
    name: "rflutter_alert Flutter Package",
    url: "https://pub.dev/packages/rflutter_alert",
    description: "Flutter package for creating alerts.",
    tags: ["Flutter", "alerts"],
    categories: "Development",
  },
  {
    id: 20,
    name: "Flutter Course Resources - GitHub",
    url: "https://github.com/londonappbrewery/Flutter-Course-Resources/",
    description: "GitHub repository with resources for Flutter courses.",
    tags: ["Flutter", "resources"],
    categories: "Development",
  },
  {
    id: 21,
    name: "Material Library - Dart API",
    url: "https://api.flutter.dev/flutter/material/material-library.html#classes",
    description: "Documentation for Flutter's material library.",
    tags: ["Flutter", "documentation"],
    categories: "Development",
  },
  {
    id: 22,
    name: "Cloud Firestore Security Rules",
    url: "https://firebase.google.com/docs/firestore/security/get-started",
    description:
      "Documentation for getting started with Firestore security rules.",
    tags: ["Firebase", "security"],
    categories: "Development",
  },
  {
    id: 23,
    name: "Responsive Side Navigation Bar in Flutter",
    url: "https://morioh.com/p/ea80244a41b3",
    description:
      "Guide on creating a responsive side navigation bar in Flutter.",
    tags: ["Flutter", "UI"],
    categories: "Development",
  },
  {
    id: 24,
    name: "Flutter Countdown Timer - YouTube",
    url: "https://www.youtube.com/watch?v=bjAsnIw3VCs",
    description: "YouTube tutorial on creating a countdown timer in Flutter.",
    tags: ["Flutter", "timer"],
    categories: "Development",
  },
  {
    id: 25,
    name: "fluent_ui Flutter Package",
    url: "https://pub.dev/packages/fluent_ui",
    description: "Package for creating Windows-style UI components in Flutter.",
    tags: ["Flutter", "UI"],
    categories: "Development",
  },
  {
    id: 26,
    name: "Collapsible Drawer - GitHub",
    url: "https://github.com/BenjaminMahmic/collapsible_drawer/tree/main/lib",
    description:
      "GitHub repository for a Flutter collapsible drawer component.",
    tags: ["Flutter", "UI"],
    categories: "Development",
  },
  {
    id: 27,
    name: "Chat App UI - GitHub",
    url: "https://github.com/BenjaminMahmic/Chat-App-UI",
    description: "GitHub repository for a chat app UI built with Flutter.",
    tags: ["Flutter", "chat"],
    categories: "Development",
  },
  {
    id: 28,
    name: "Get Image from Firebase Storage in Flutter",
    url: "https://medium.com/vijay-r/get-image-from-firebase-storage-in-flutter-web-e89280826ad3",
    description: "Guide on retrieving images from Firebase storage in Flutter.",
    tags: ["Flutter", "Firebase"],
    categories: "Development",
  },
  {
    id: 29,
    name: "WhatTheFont - MyFonts",
    url: "https://www.myfonts.com/pages/whatthefont",
    description: "Tool for identifying fonts from images.",
    tags: ["fonts", "design"],
    categories: "Design",
  },
];
