/** @format */

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReduxProviders, ThemeProviders } from "./providers";
import NavBar from "@/components/NavBar";
import TailwindScreenIndicators from "@/components/TailwindScreenIndicators";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProviders>
          <ThemeProviders>
            <NavBar />
            <main className={`mx-auto max-w-[104rem] px-5 pt-24`}>
              {children}
            </main>
            <TailwindScreenIndicators />
          </ThemeProviders>
        </ReduxProviders>
      </body>
    </html>
  );
}
